### ISSUE TITLE
True positive issues

### ISSUE THREAD

**Issue by Ivan1905** [tf0rs/forta-address-poisoning-agent#1]
I have reviewed some alerts for the month of April and saw a bunch of alerts that from my assessment they shouldn't be considered as TP.
It seems that the bot is firing every time there's a bulk transaction.
E.g: 0xdead5755e7c08d537834933498b2841e071fe349 was flagged as an address poisoner address.
Forta alert: https://explorer.forta.network/alert/0x8154ff181646eee2769faf9108c2c456a7fc2763f903a245867871c861592b6c
Scan link: https://etherscan.io/address/0xdead5755e7c08d537834933498b2841e071fe349

e.g2: 0xa3096ecc4ae1ab833e3f54fbf371873211822b41 was flagged as an address poisoner address.
Forta alert: https://explorer.forta.network/alert/0x52a3bc412ca246c3ff780c3ae48b470525a5d7771b19d77b13909ae1b3d45b80
Scan link: https://etherscan.io/address/0xa3096ecc4ae1ab833e3f54fbf371873211822b41

Both cases alerts seem to trigger right after the "bulk transfer"

**Comment by tf0rs** [comment]
The issue is that the OpenSea : Transfer Helper (0x0000000000c2d145a2526bd8c716263bfebe1a72) was flagged as an address poisoning contract, which per the agent's logic means every transaction calling it will be alerted on as address poisoning. I've pushed a hot fix, but will investigate further to identify and mitigate the false positive that caused this.
